import './styles/global.css';

import { cn } from '@client/lib/cn';
import { DarkModeProvider } from './providers/darkmode';
import { Header } from './components/Header';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('relative h-screen w-full')}>
        <DarkModeProvider>
          <Header />
          {children}
        </DarkModeProvider>
      </body>
    </html>
  );
}
