import '@/ui/styles';

import { cn } from '@/util';
import { inter } from './fonts';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('relative h-screen w-full', inter.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
